### ISSUE TITLE
Does not export REDIS_URL

### ISSUE THREAD

**Issue by msakrejda** [heroku/heroku-buildpack-ci-redis#1]
The buildpack starts Redis with a predefined, hard-coded configuration. It currently requires buildpack consumers to also make those assumptions. For flexibility and consistency with the Postgres CI buildpack, this buildpack should export a REDIS_URL.

**Comment by sigmavirus24** [comment]
Just ran into this trying to get Heroku CI set up for Connect.

**Comment by msakrejda** [comment]
Woo! Thanks!
