### ISSUE TITLE
Username "h" in connection string results in WRONGPASS errors for Redis 6+

### ISSUE THREAD

**Issue by iriberri** [heroku/heroku-buildpack-ci-redis#30]
In the past, Heroku was adding the `h` username on Redis connection strings (see: https://devcenter.heroku.com/changelog-items/1932). With the release of Redis 6 and ACLs (https://redis.io/docs/manual/security/acl/), Heroku stopped adding the `h` username for Redis 6 instances (and new Redis add-ons using older Redis versions).

However, this buildpack is still hardcoding the `h` username:  https://github.com/heroku/heroku-buildpack-ci-redis/blob/master/bin/compile#L68 in the connection string config var.

This is resulting in `WRONGPASS invalid username-password pair or user is disabled.` errors with Redis 6+ if the Redis clients are trying to authenticate using the `h` username and the given password.

With Redis 6+, using `requirepass` will configure that pass for the `default` user. The `h` user wouldn't exist, neither it's configured with that password, so connections using `username=h, password=xxxx` would fail. (Although one could use `username=default, password=xxx` and that'd work). We run `requirepass` here: https://github.com/heroku/heroku-buildpack-ci-redis/blob/master/bin/compile#L71.

We've seen reports of this issue after 6.2 was made the default version as part of https://github.com/heroku/heroku-buildpack-ci-redis/pull/29. I'm admittedly confused as of why we didn't get reports of the same problem before, when 6.0.9 was the default version, which should have worked similarly in terms of users/ACLs.

As a result, this is resulting in test failures in Heroku CI when the Redis client tries to connect to the locally running instance and authenticate as the `h` user. We've seen this happen with `redis-py` (3.5.3, and also tested with 4.3.1 through a console directly - outside of Heroku CI).

Some other clients like `redis-rb` are handling this scenario specifically but raising a warning:

```
[redis-rb] The Redis connection was configured with username "h", but the provided password was for the default user. This will start failing in redis-rb 5.0.0.
```
(https://github.com/redis/redis-rb/blob/4724c1bfde2d5679128ced8ec7b46bac66605b7b/lib/redis/client.rb#L124-L134)

To sort this out, the `REDIS_URL` config var shouldn't include the `h` username at least if the version is 6 or higher.

**Comment by edmorley** [comment]
Ah so the reason this only started being an issue now, is that whilst #22 added support for Redis 6.0 (and made it the buildpack default) in Nov 2020, the buildpack appears not to have been published to the buildpack registry then (which is what the in-dyno CI feature fetches from).

As such, #22 wasn't deployed until the recent changes were deployed. The release history can be seen here:
https://github.com/heroku/heroku-buildpack-ci-redis/pull/29#issuecomment-1131402442

**Comment by alaa-awartany** [comment]
Thank you @iriberri for the fix, we can confirm that we no longer face this issue.
